# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-15 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='added_by',
        ),
    ]
